import { type SajuAnalysis } from '../../domain/SajuAnalysis.js';
import { type SaeunPillar } from '../../domain/SaeunInfo.js';
import { type Ohaeng } from '../../domain/Ohaeng.js';
import { type PillarPosition } from '../../domain/PillarPosition.js';
import { type CheonganRelationHit, type HapHwaEvaluation, type JijiRelationHit, type ResolvedRelation, type ScoredCheonganRelation, type ShinsalComposite, type WeightedShinsalHit } from '../../domain/Relations.js';
import { type StrengthResult } from '../../domain/StrengthResult.js';
import { type GyeokgukResult } from '../../domain/Gyeokguk.js';
import { type YongshinResult } from '../../domain/YongshinResult.js';
import { type ShinsalHit } from '../../domain/Shinsal.js';
import { type DaeunInfo } from '../../domain/DaeunInfo.js';
import { type PalaceAnalysis } from '../../domain/Palace.js';
import { type TenGodAnalysis } from '../../domain/TenGodAnalysis.js';
import { type SibiUnseong } from '../../domain/SibiUnseong.js';
import { type AnalysisTraceStep } from '../../domain/types.js';
import { type SajuPillarResult } from '../SajuCalculator.js';
import { type GongmangResult } from '../analysis/GongmangCalculator.js';
export interface FinalAnalysisContext {
    coreResult: SajuPillarResult;
    rawJijiRelations: JijiRelationHit[];
    cheonganRelations: CheonganRelationHit[];
    hapHwaEvaluations: HapHwaEvaluation[];
    resolvedJijiRelations: ResolvedRelation[];
    scoredCheonganRelations: ScoredCheonganRelation[];
    sibiUnseong: Map<PillarPosition, SibiUnseong>;
    gongmang: GongmangResult;
    strength: StrengthResult;
    yongshin: YongshinResult;
    gyeokguk: GyeokgukResult;
    shinsalHits: ShinsalHit[];
    weightedShinsalHits: WeightedShinsalHit[];
    shinsalComposites: ShinsalComposite[];
    palace: Record<PillarPosition, PalaceAnalysis>;
    daeun: DaeunInfo;
    saeun: SaeunPillar[];
    ohaengDistribution: Map<Ohaeng, number>;
    trace: AnalysisTraceStep[];
    tenGodAnalysis: TenGodAnalysis;
}
export declare function buildAnalysisResults(context: FinalAnalysisContext): Map<string, unknown>;
export declare function buildSajuAnalysis(context: FinalAnalysisContext): SajuAnalysis;
//# sourceMappingURL=SajuAnalysisAssembler.d.ts.map