import type { EngineConfig } from '../api/types.js';
import type { PillarIdx, StemIdx } from '../core/cycle.js';
import type { LocalDate, LocalDateTime, LocalTime } from './iso.js';
import type { JieBoundariesAround, SolarTermInstant, SolarTermMethod } from './solarTerms.js';
export declare function addDays(date: LocalDate, days: number): LocalDate;
export declare function compareLocalDateTime(a: LocalDateTime, b: LocalDateTime): number;
export declare function effectiveDayDate(ldt: LocalDateTime, dayBoundary: EngineConfig['calendar']['dayBoundary']): LocalDate;
export declare function calcDayPillar(localDate: LocalDate): PillarIdx;
export declare function calcHourPillar(dayStem: StemIdx, localTime: LocalTime, _hourBoundary: EngineConfig['calendar']['hourBoundary']): PillarIdx;
export declare function monthOrderFromJieBoundaries(utcMs: number, boundaries: SolarTermInstant[]): number;
export declare function calcYearPillarFromLiChunUtc(localYear: number, utcMs: number, liChunUtcMs: number | null, yearBoundary: EngineConfig['calendar']['yearBoundary'], offsetMinutes: number, solarTermMethod: SolarTermMethod): PillarIdx;
export declare function calcYearPillar(ldt: LocalDateTime, yearBoundary: EngineConfig['calendar']['yearBoundary']): PillarIdx;
export declare function calcMonthPillarFromOrder(yearStem: StemIdx, monthOrder: number): PillarIdx;
export declare function calcMonthPillar(_ldt: LocalDateTime, _yearStem: StemIdx, monthBoundary: EngineConfig['calendar']['monthBoundary']): PillarIdx;
export declare function gregorianMonthOrder(m: number): number;
export declare function liChunUtcMsFromBoundaries(boundariesAround: JieBoundariesAround): number | null;
export declare function monthOrderByPolicy(utcMs: number, ldt: LocalDateTime, monthBoundary: EngineConfig['calendar']['monthBoundary'], jieBoundariesAround: JieBoundariesAround | null): number;
